services:
  web:
    build: .
    container_name: smart_school_app
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - smart_school_network

  webserver:
    image: arm64v8/nginx:latest
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - smart_school_network

  db:
    image: mariadb:latest
    container_name: mariadb_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smart_school_network
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - smart_school_network
volumes:
  db_data:

networks:
  smart_school_network:
    driver: bridge
