name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.143.102.187 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: ssh ubuntu@185.143.102.187 "cd /var/www/learning && sudo git pull origin main"
